name: edwardstcole_roomme_challenge
description: RoomMe Onboarding Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^4.0.4
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.6.14
  firebase_core: ^2.10.0
  cloud_firestore: ^4.0.1
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/uva.png
    - assets/images/jmu.png
    - assets/images/va-tech.png
    - assets/images/cole-edwards.jpg

