// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWNnsZPojFy0pyD9Kc6QZnPyBgsYez1Y',
    appId: '1:340738516739:web:c945063baf8ec500d16b36',
    messagingSenderId: '340738516739',
    projectId: 'edwardstcole-roomme-challenge',
    authDomain: 'edwardstcole-roomme-challenge.firebaseapp.com',
    storageBucket: 'edwardstcole-roomme-challenge.appspot.com',
    measurementId: 'G-BH77BMVR23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BJ_c6iUz3JdLmUtXfPBWxkkrixP2nsk',
    appId: '1:340738516739:android:c2b6327ba69cbe18d16b36',
    messagingSenderId: '340738516739',
    projectId: 'edwardstcole-roomme-challenge',
    storageBucket: 'edwardstcole-roomme-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2y1Iqt72lDoFvf0pjpY6anOWQijLx3I',
    appId: '1:340738516739:ios:32b48edeb8af4311d16b36',
    messagingSenderId: '340738516739',
    projectId: 'edwardstcole-roomme-challenge',
    storageBucket: 'edwardstcole-roomme-challenge.appspot.com',
    iosClientId: '340738516739-1e4f45j7d844q2oddc3277tahlarsl61.apps.googleusercontent.com',
    iosBundleId: 'com.example.edwardstcoleRoommeChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2y1Iqt72lDoFvf0pjpY6anOWQijLx3I',
    appId: '1:340738516739:ios:32b48edeb8af4311d16b36',
    messagingSenderId: '340738516739',
    projectId: 'edwardstcole-roomme-challenge',
    storageBucket: 'edwardstcole-roomme-challenge.appspot.com',
    iosClientId: '340738516739-1e4f45j7d844q2oddc3277tahlarsl61.apps.googleusercontent.com',
    iosBundleId: 'com.example.edwardstcoleRoommeChallenge',
  );
}
